name: Build and Deploy Containers

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  container_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - variant: local-base
            module: local/base
            image: feature-launcher-local-base
            readme: local/base/README.md
          - variant: remote-base
            module: remote/base
            image: feature-launcher-remote-base
            readme: remote/base/README.md
          - variant: local-directory-installer
            module: local/directory-installer
            image: feature-launcher-local-directory-installer
            readme: local/directory-installer/README.md
          - variant: remote-http-installer
            module: remote/http-installer
            image: feature-launcher-remote-http-installer
            readme: remote/http-installer/README.md

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0

      - name: Set up JDK
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Download dependencies
        run: mvn dependency:copy-dependencies -pl ${{ matrix.module }} -am -DexcludeTransitive=true -DincludeScope=compile

      - name: Update dockerhub repo description
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: peter-evans/dockerhub-description@432a30c9e07499fd01da9f8a49f0faf9e0ca5b77 # v4.0.2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: eclipseosgitech/${{ matrix.image }}
          readme-filepath: ./${{ matrix.readme }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.2.1
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Login to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to Github Docker Registry
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Multi-Arch Docker Image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ./${{ matrix.module }}
          file: ./${{ matrix.module }}/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
          tags: |
            ghcr.io/eclipse-osgi-technology/${{ matrix.image }}:snapshot
